# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: MaxNoragami/tum-web-lab2
  branch: main

i18n:
  structure: multiple_folders
  locales: [ro, en]
  default_locale: ro

media_folder: public
public_folder: /

singletons:
  - name: global
    label: Global
    file: src/content/{{locale}}/global.json
    i18n: true
    fields:
      - { label: CTA Text, name: cta_text, widget: string, i18n: true }

  - name: hero
    label: Hero Section
    file: src/content/{{locale}}/hero.json
    media_folder: /public/section-hero
    public_folder: /section-hero
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true, hint: "Wrap words in **double asterisks** to highlight them" }
      - { label: Description, name: description, widget: string, i18n: true }

  - name: about-me
    label: About Me Section
    file: src/content/{{locale}}/about-me.json
    media_folder: /public/section-about-me
    public_folder: /section-about-me
    i18n: true
    fields:
      - { label: Section Title, name: section_title, widget: string, i18n: true }
      - { label: Greeting, name: greeting, widget: string, i18n: true, hint: "Wrap name in **double asterisks** to highlight" }
      - { label: Quote, name: quote, widget: string, i18n: true }
      - { label: Paragraph 1, name: paragraph_1, widget: text, i18n: true, hint: "Wrap words in **double asterisks** to highlight" }
      - { label: Paragraph 2, name: paragraph_2, widget: text, i18n: true, hint: "Wrap words in **double asterisks** to highlight" }
      - { label: Image, name: image, widget: image, i18n: duplicate }
      - { label: Image Alt Text, name: image_alt, widget: string, i18n: true }

  - name: gallery
    label: Gallery Section
    file: src/content/{{locale}}/gallery.json
    media_folder: /public/section-gallery
    public_folder: /section-gallery
    i18n: true
    fields:
      - { label: Section Title, name: section_title, widget: string, i18n: true }
      - label: Images
        name: images
        widget: list
        i18n: true
        fields:
          - { label: Image, name: src, widget: image, i18n: duplicate }
          - { label: Alt Text, name: alt, widget: string, i18n: true }

